WebApplication3/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplication3.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

WebApplication3/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplication3.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

WebApplication3/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplication3.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

WebApplication3/Pages/RESTAURANT/ClientRestaurant.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace WebApplication3.Pages.RESTAURANT
{
    public class ClientRestaurantModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

WebApplication3/Pages/RESTAURANT/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using webapplication3.Data;
using ClassLibrary1;
namespace WebApplication3.Pages.RESTAURANT
{
    public class DeleteModel : PageModel
    {
        private readonly IRestaurantData restaurantData;
        public Restaurant Restaurant { get; set; } 
        public DeleteModel(IRestaurantData restaurantData)
        {
            this.restaurantData = restaurantData;
        }
        public IActionResult OnGet(int restaurantId)
        {
            Restaurant = restaurantData.GetById(restaurantId);
            if (Restaurant==null)
            {
                return RedirectToPage("./NotFound");
            }
            return Page();
        }

        public IActionResult onPost(int restaurantId)
        {
             var restaurant = restaurantData.Delete(restaurantId);
            restaurantData.Commit();

            if (restaurant==null)
            {
                return RedirectToPage("./NotFound");
            }
            TempData["Message"] = $"{restaurant.name} Deleted";
            return RedirectToPage("/List");
        }
    }
}

WebApplication3/Pages/RESTAURANT/Detail.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ClassLibrary1;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using webapplication3.Data;

namespace WebApplication3.Pages.RESTAURANT
{
    public class DetailModel : PageModel
    {
        private readonly IRestaurantData restaurantData;

        [TempData]
        public string Message { get; set; }
        public Restaurant Restaurant { get; set; }
        public DetailModel(IRestaurantData restaurantData)
        {
            this.restaurantData = restaurantData;
        }
        public IActionResult onGet(int restaurantId)
        {
            Restaurant = restaurantData.GetById(restaurantId);
            if(Restaurant==null)
            {
                return RedirectToPage("./NotFound");
            }
            return Page();
        }
    }
}

WebApplication3/Pages/RESTAURANT/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using webapplication3.Data;
using ClassLibrary1;


namespace WebApplication3.Pages.RESTAURANT
{
    public class EditModel : PageModel
    {
        private readonly IRestaurantData restaurantData;
        private readonly IHtmlHelper htmlhelper;

        [BindProperty]
        public Restaurant Restaurant { get ; set ; }

        public IEnumerable< SelectListItem >Cuisines{ get; set; }
        public EditModel(IRestaurantData restaurantData,IHtmlHelper htmlHelper)
        {
            this.restaurantData = restaurantData;
            this.htmlhelper = htmlHelper;
        }
        public IActionResult OnGet(int? restaurantId)
        {
            Cuisines = htmlhelper.GetEnumSelectList<CuisineType>();
            if(restaurantId.HasValue)
            {
                Restaurant = restaurantData.GetById(restaurantId.Value);
            }
            else
            {
                Restaurant = new Restaurant();
               
            }
            
            if(Restaurant==null)
            {
                return RedirectToPage("./NotFound");

            }
            return Page();

        }
        public IActionResult onPost(int? restaurantId)
        {
            if(!ModelState.IsValid)
            {
                Cuisines = htmlhelper.GetEnumSelectList<CuisineType>();

                return Page();

            }
            if(Restaurant.id>0)
            {
                restaurantData.Update(Restaurant);
            }
           else
            {
                restaurantData.Add(Restaurant);

            }
            restaurantData.Commit();
            TempData["Message"] = "Restaurant Saved !";
            return RedirectToPage("./Detail", new { restaurantId = Restaurant.id });

        }


    }
}

WebApplication3/Pages/RESTAURANT/List.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ClassLibrary1;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Configuration;
using webapplication3.Data;
using webapplication3;


namespace WebApplication3.Pages.RESTAURANT
{
    public class ListModel : PageModel
    {
        private readonly IConfiguration config;
        private readonly IRestaurantData restaurantData;

        public string Message { get; set; }
        public IEnumerable<Restaurant> Restaurants { get; set; }
        
        [BindProperty(SupportsGet =true)]
       public string SearchTerm { get; set; }

        public ListModel ( IConfiguration config , IRestaurantData restaurantData)
        {
            this.config = config;
            this.restaurantData= restaurantData;
        }
        public void OnGet()
        {
           
            Message = config["Message"];
            Restaurants = restaurantData.GetRestaurantsByName(SearchTerm);
        }
    }
}

WebApplication3/Pages/RESTAURANT/_Summary.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace WebApplication3.Pages.RESTAURANT
{
    public class _SummaryModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

WebApplication3/Pages/ViewComponents/RestaurantCountViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

using Microsoft.AspNetCore.Mvc;
using webapplication3.Data;

namespace WebApplication3.Pages.ViewComponents
{
    public class RestaurantCountViewComponent : ViewComponent
    {
        private readonly IRestaurantData restaurantData;
        public RestaurantCountViewComponent(IRestaurantData restaurantData)
        {
            this.restaurantData = restaurantData;
        }
        public IViewComponentResult Invoke()
        {
            var count = restaurantData.GetCountOfRestaurants();
            return View(count);
        }
    }
}

WebApplication3/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
 
</div>
<div>
    Hii !!
</div>

WebApplication3/Pages/RESTAURANT/ClientRestaurant.cshtml
@page
@model WebApplication3.Pages.RESTAURANT.ClientRestaurantModel
@{
    ViewData["Title"] = "ClientRestaurants";
}
<h2> Client Restaurants</h2>

@section Scripts{

<environment include="Development">

</environment>

<environment exclude="Development">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs/dt-1.11.3/datatables.min.css" />

    <script type="text/javascript" src="https://cdn.datatables.net/v/bs/dt-1.11.3/datatables.min.js"></script>
</environment>
    
    
    <script>



        $(function () {
            $.ajax("/api/restaurants/",

                { method: "get" })

                .then(function (response) {

                    console.dir(response);

                });
        });



    </script>
}

WebApplication3/Pages/RESTAURANT/Delete.cshtml
@page "{restaurantId}"
@model WebApplication3.Pages.RESTAURANT.DeleteModel
@{
    ViewData["Title"] = "Delete";
}
}

<h2>Delete !</h2>
<div class="alert alert-danger">
    Are you sure you want to delete @Model.Restaurant.name?
</div>
<form method="post">
    <button type="submit" class="btn btn-danger">Yes</button>
    <a asp-page=" List" class="btn btn-default">Cancel</a>
</form>

WebApplication3/Pages/RESTAURANT/Detail.cshtml
@page  "{restaurantId:int}"

@model WebApplication3.Pages.RESTAURANT.DetailModel
@{
    ViewData["Title"] = "Detail";
}

<h2>@Model.Restaurant.name</h2>
<div>
    Id: @Model.Restaurant.id
</div>
<div>
   Location: @Model.Restaurant.location
</div>
<div>
    Cuisine: @Model.Restaurant.Cuisine
</div>

@if(Model.Message!=null)
            {
    <div class="alert alert-info">@Model.Message</div>
            }
<a asp-page="./List" class="btn btn-default">All Restaurant</a>

WebApplication3/Pages/RESTAURANT/Edit.cshtml
@page "{restaurantId:int?}"
@model WebApplication3.Pages.RESTAURANT.EditModel
@{
    ViewData["Title"] = "Edit";
}
<h2>Editing @Model.Restaurant.name</h2>

<form method="post">

    <input type="hidden" asp-for="Restaurant.id" />
    <div class="form-group">
        <label asp-for="Restaurant.name"></label>
        <input asp-for="Restaurant.name" class="form-control" />
        <span class="text-danger" asp-validation-for="Restaurant.name"></span>
    </div>
    <div class="form-group">
        <label asp-for="Restaurant.location"></label>
        <input asp-for="Restaurant.location" class="form-control" />
        <span class="text-danger" asp-validation-for="Restaurant.location"></span>

    </div>
    <div class="form-group">
        <label asp-for="Restaurant.Cuisine"></label>
        <select class="form-control" asp-for="Restaurant.Cuisine" asp-items="Model.Cuisines">
        </select>
        <span class="text-danger" asp-validation-for="Restaurant.Cuisine"></span>

    </div>
    <button type="submit" class="btn btn-primary"> Save </button>
</form>
@section Scripts{
                <partial name="_ValidationScriptsPartial" />
            }

WebApplication3/Pages/RESTAURANT/List.cshtml
@page
@model WebApplication3.Pages.RESTAURANT.ListModel
@{
    ViewData["Title"] = "Restaurants";
}

<h1>RESTAURANTS</h1>


<form method="get">

    <div class="form-group">
        <div class="input-group">
            <input type="search" class="form-control" asp-for="SearchTerm" />
            <span class="input-group-btn">
                <button class="btn btn-default">
                    <i class="glyphicon glyphicon-search"></i>
                </button>
            </span>
        </div>
    </div>
</form>

@foreach (var restaurants in Model.Restaurants)
{
    <partial name="_Summary" model="restaurants" />
}
<a asp-page=".\Edit" class="btn btn-primary"> Add New</a>

@section footer{

    <div> @Model.Message</div>
}

WebApplication3/Pages/RESTAURANT/NotFound.cshtml
@page
@{ 
    ViewData["Title"] = "NotFound";

}
<h2>Your Restaurant was not Found</h2>
<a asp-page="./List" class="btn btn-primary">See All Restaurants</a>

WebApplication3/Pages/RESTAURANT/_Summary.cshtml
@using ClassLibrary1;


@model Restaurant

<div class="panel panel-default">
    <div class="panel-heading">
        <h3>@Model.name</h3>
    </div>
    <div class="panel-body">
        <span> Location : @Model.location</span>
        <span>Cuisine : @Model.Cuisine</span>
    </div>
    <div class="panel-footer">
        <a class="btn btn-lg" asp-page="./Detail"
           asp-route-restaurantid="@Model.id">
            <i class="glyphicon glyphicon-zoom-in"></i>
        </a>
        <a class="btn btn-lg" asp-page="./Edit"
           asp-route-restaurantid="@Model.id">
            <i class="glyphicon glyphicon-edit"></i>
        </a>
        <a class="btn btn-lg" asp-page="./Delete"
           asp-route-restaurantid="@Model.id">
            <i class="glyphicon glyphicon-trash"></i>
        </a>
    </div>
</div>

WebApplication3/Pages/Shared/Components/RestaurantCount/Default.cshtml
@model int


<div class="well">
    There are @Model restaurants here .<a asp-page="/Restaurants/List">see them all</a>
</div>

WebApplication3/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApplication3</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">WebApplication3</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/RESTAURANT/List">Restaurant</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
        <footer>
            <vc:restaurant-count></vc:restaurant-count> 
            @RenderSection("footer",required: false)
            <p>&copy;2018-Restaurant</p>
        </footer>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - WebApplication3 - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>